### ISSUE TITLE
[Bug] Exception while registering commands

### ISSUE THREAD

**Issue by xmassi47** [HunHage/SlashLib#13]
__**Description**__
Since i updated my Discord4J Version from 3.2.2 to 3.2.3 i am getting registering exceptions

__**Discord4J and SlashLib Versions**__
- Discord4J: 3.2.3
- SlashLib: 1.2.2

__**Exception i get**__
`Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String discord4j.discordjson.json.ApplicationCommandData.id()'
	at net.exploitables.slashlib.CommandRegister.validateGlobalCommands(CommandRegister.java:308)
	at net.exploitables.slashlib.CommandRegister.registerGlobalCommands(CommandRegister.java:155)
	at dev.massi.arises.ArisesApplication.main(ArisesApplication.java:68)`

**Comment by HunHage** [comment]
`NoSuchMethod` error is highly likely due to D4J and its dependencies updating. I will take a look soon and release a patch. Thank you for letting me know.

**Comment by HunHage** [comment]
It was just the `Id` type changing with D4J, I released a new version for v3.2.3. There is a deprecated method being used for permissions v1 but I did not see it detect a false positive when updating permissions in a guild. Let me know if you experience unnecessary command updates.
